// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/opamp/proto/opamp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentToServer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstanceUid     string                 `protobuf:"bytes,1,opt,name=instance_uid,json=instanceUid,proto3" json:"instance_uid,omitempty"`
	EffectiveConfig string                 `protobuf:"bytes,2,opt,name=effective_config,json=effectiveConfig,proto3" json:"effective_config,omitempty"`
	SequenceNum     int64                  `protobuf:"varint,3,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentToServer) Reset() {
	*x = AgentToServer{}
	mi := &file_internal_opamp_proto_opamp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToServer) ProtoMessage() {}

func (x *AgentToServer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_opamp_proto_opamp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToServer.ProtoReflect.Descriptor instead.
func (*AgentToServer) Descriptor() ([]byte, []int) {
	return file_internal_opamp_proto_opamp_proto_rawDescGZIP(), []int{0}
}

func (x *AgentToServer) GetInstanceUid() string {
	if x != nil {
		return x.InstanceUid
	}
	return ""
}

func (x *AgentToServer) GetEffectiveConfig() string {
	if x != nil {
		return x.EffectiveConfig
	}
	return ""
}

func (x *AgentToServer) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

type ServerToAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceUid   string                 `protobuf:"bytes,1,opt,name=instance_uid,json=instanceUid,proto3" json:"instance_uid,omitempty"`
	RemoteConfig  string                 `protobuf:"bytes,2,opt,name=remote_config,json=remoteConfig,proto3" json:"remote_config,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,3,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToAgent) Reset() {
	*x = ServerToAgent{}
	mi := &file_internal_opamp_proto_opamp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToAgent) ProtoMessage() {}

func (x *ServerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_opamp_proto_opamp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToAgent.ProtoReflect.Descriptor instead.
func (*ServerToAgent) Descriptor() ([]byte, []int) {
	return file_internal_opamp_proto_opamp_proto_rawDescGZIP(), []int{1}
}

func (x *ServerToAgent) GetInstanceUid() string {
	if x != nil {
		return x.InstanceUid
	}
	return ""
}

func (x *ServerToAgent) GetRemoteConfig() string {
	if x != nil {
		return x.RemoteConfig
	}
	return ""
}

func (x *ServerToAgent) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

var File_internal_opamp_proto_opamp_proto protoreflect.FileDescriptor

const file_internal_opamp_proto_opamp_proto_rawDesc = "" +
	"\n" +
	" internal/opamp/proto/opamp.proto\x12\x05opamp\"\x80\x01\n" +
	"\rAgentToServer\x12!\n" +
	"\finstance_uid\x18\x01 \x01(\tR\vinstanceUid\x12)\n" +
	"\x10effective_config\x18\x02 \x01(\tR\x0feffectiveConfig\x12!\n" +
	"\fsequence_num\x18\x03 \x01(\x03R\vsequenceNum\"z\n" +
	"\rServerToAgent\x12!\n" +
	"\finstance_uid\x18\x01 \x01(\tR\vinstanceUid\x12#\n" +
	"\rremote_config\x18\x02 \x01(\tR\fremoteConfig\x12!\n" +
	"\fsequence_num\x18\x03 \x01(\x03R\vsequenceNum2I\n" +
	"\fOpAMPService\x129\n" +
	"\aConnect\x12\x14.opamp.AgentToServer\x1a\x14.opamp.ServerToAgent(\x010\x01B5Z3github.com/conduit-obs/conduit/internal/opamp/protob\x06proto3"

var (
	file_internal_opamp_proto_opamp_proto_rawDescOnce sync.Once
	file_internal_opamp_proto_opamp_proto_rawDescData []byte
)

func file_internal_opamp_proto_opamp_proto_rawDescGZIP() []byte {
	file_internal_opamp_proto_opamp_proto_rawDescOnce.Do(func() {
		file_internal_opamp_proto_opamp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_opamp_proto_opamp_proto_rawDesc), len(file_internal_opamp_proto_opamp_proto_rawDesc)))
	})
	return file_internal_opamp_proto_opamp_proto_rawDescData
}

var file_internal_opamp_proto_opamp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_opamp_proto_opamp_proto_goTypes = []any{
	(*AgentToServer)(nil), // 0: opamp.AgentToServer
	(*ServerToAgent)(nil), // 1: opamp.ServerToAgent
}
var file_internal_opamp_proto_opamp_proto_depIdxs = []int32{
	0, // 0: opamp.OpAMPService.Connect:input_type -> opamp.AgentToServer
	1, // 1: opamp.OpAMPService.Connect:output_type -> opamp.ServerToAgent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_opamp_proto_opamp_proto_init() }
func file_internal_opamp_proto_opamp_proto_init() {
	if File_internal_opamp_proto_opamp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_opamp_proto_opamp_proto_rawDesc), len(file_internal_opamp_proto_opamp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_opamp_proto_opamp_proto_goTypes,
		DependencyIndexes: file_internal_opamp_proto_opamp_proto_depIdxs,
		MessageInfos:      file_internal_opamp_proto_opamp_proto_msgTypes,
	}.Build()
	File_internal_opamp_proto_opamp_proto = out.File
	file_internal_opamp_proto_opamp_proto_goTypes = nil
	file_internal_opamp_proto_opamp_proto_depIdxs = nil
}
