// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/opamp/proto/opamp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpAMPService_Connect_FullMethodName = "/opamp.OpAMPService/Connect"
)

// OpAMPServiceClient is the client API for OpAMPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpAMPServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error)
}

type opAMPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpAMPServiceClient(cc grpc.ClientConnInterface) OpAMPServiceClient {
	return &opAMPServiceClient{cc}
}

func (c *opAMPServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OpAMPService_ServiceDesc.Streams[0], OpAMPService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToServer, ServerToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpAMPService_ConnectClient = grpc.BidiStreamingClient[AgentToServer, ServerToAgent]

// OpAMPServiceServer is the server API for OpAMPService service.
// All implementations must embed UnimplementedOpAMPServiceServer
// for forward compatibility.
type OpAMPServiceServer interface {
	Connect(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error
	mustEmbedUnimplementedOpAMPServiceServer()
}

// UnimplementedOpAMPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpAMPServiceServer struct{}

func (UnimplementedOpAMPServiceServer) Connect(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedOpAMPServiceServer) mustEmbedUnimplementedOpAMPServiceServer() {}
func (UnimplementedOpAMPServiceServer) testEmbeddedByValue()                      {}

// UnsafeOpAMPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpAMPServiceServer will
// result in compilation errors.
type UnsafeOpAMPServiceServer interface {
	mustEmbedUnimplementedOpAMPServiceServer()
}

func RegisterOpAMPServiceServer(s grpc.ServiceRegistrar, srv OpAMPServiceServer) {
	// If the following call panics, it indicates UnimplementedOpAMPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpAMPService_ServiceDesc, srv)
}

func _OpAMPService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OpAMPServiceServer).Connect(&grpc.GenericServerStream[AgentToServer, ServerToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpAMPService_ConnectServer = grpc.BidiStreamingServer[AgentToServer, ServerToAgent]

// OpAMPService_ServiceDesc is the grpc.ServiceDesc for OpAMPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpAMPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opamp.OpAMPService",
	HandlerType: (*OpAMPServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _OpAMPService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/opamp/proto/opamp.proto",
}
